from selenium.webdriver.common.by import By


from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
ask_for_a_taxi_button = (By.XPATH, '//button[@class="button round"]')
comfort_button = (By.XPATH, "//div[@class='tcard-title' and text ()='Comfort']")
telephone_number_field = (By.XPATH, '//div[@class="np-text"]')
number_phone = (By.ID, 'phone')
next_button = (By.XPATH, "//button[contains(@class, 'button') and text()='Siguiente']")
code_phone = (By.ID, 'code')
confirm_code = (By.XPATH, "//button[contains(@class, 'button') and text()='Confirmar']")
payment_method = (By.CLASS_NAME, 'pp-text')
add_card_button = (By.XPATH, "//div[@class='pp-title' and text()='Agregar tarjeta']")
card_number = (By.CSS_SELECTOR, '.card-input:nth-of-type(1)')
card_code = (By.XPATH, '//input[@name="code"]')
add_button = (By.XPATH, "//button[contains(@class, 'button full') and text()='Agregar']")
message_to_driver = (By.ID, 'comment')
close_payment_method_modal = (By.XPATH, '//div[@class="payment-picker open"]//button[@class="close-button section-close"]')
activate_button = (By.CSS_SELECTOR, '.slider:nth-of-type(1)')
increment_button = (By.XPATH, "//div[@class= 'r-group-items'] //div[@class= 'r-counter'] //div[@class= 'counter-plus']")
ice_cream_counter = (By.CSS_SELECTOR, '.counter-value:nth-of-type(2)')
request_a_taxi = (By.CLASS_NAME, 'smart-button-wrapper')